apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc
  namespace: default
spec:
  selector:
    app: {{ .Release.Name }} 
  type: ClusterIP 
  ports:
    - name: jellyfin-port
      protocol: TCP
      port: 8096 
      targetPort: jellyfin-port
---

